# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce01aef744cc33bbae561f82a5fb5eb9ae46b7ce238b4083abf1842e524f7220ad78a81d75e28881245b3a2dbc13ed89c35b38f9d808a48a5adc6349c4737866

test:
  secret_key_base: 01d26bac8e01b9a9f2d0c01c4123fc516997ac81393419ea2a5944e053a4b877ddf80c5cab85050a67ea9b681382388bc43e47bdce6c31eb59023c95db775a2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
